apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot-k8s-demo.fullname" . }}-config
  labels:
    {{- include "springboot-k8s-demo.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
